---
title: 05. try-with-resource
section: 06.マスタ編
slug: /master/05-try-with-resource
order: 5
---

# 05. try-with-resource

<p className="goal">try-with-resource が安全でシンプルな、リソースに対する例外処理の実装方法であることを知り、
  利用できるようになること</p>

## 学習

### try-with-resource 構文を知る

Java の try-with-resource 構文で何ができるかを Web で調べてください。
検索キーワードは、「 [java try with resource](https://www.google.com/search?q=java+try+with+resource) 」です。
3 種類ぐらい説明記事やサンプルコードを読んで、try-with-resource 構文の使い方をつかみましょう。

## 練習問題 1: マルチリソース（時間: 20 分）

以下の既存コード Transcriptor クラス内の try-catch を try-with-resource の形に変更しなさい

### Transcriptor.java

```java
package master.trywith.resource.file;

import java.io.File;
import java.io.FileNotFoundException;
import java.io.PrintWriter;
import java.util.Scanner;

public class Transcriptor {

    private static final String TARGET_FILE_RELATIVE_PATH_FOR_READING 
            = "./testRead.txt";
    
        private static final String TARGET_FILE_RELATIVE_PATH_FOR_WRITING 
            = "./testWrite.txt";
    
        public static void main(String[] args) {

        Scanner scanner = null;
        PrintWriter writer = null;

        try {
            scanner = new Scanner(
                new File(TARGET_FILE_RELATIVE_PATH_FOR_READING));

            writer = new PrintWriter(
                new File(TARGET_FILE_RELATIVE_PATH_FOR_WRITING));
                
            while (scanner.hasNext()) {
                writer.print(scanner.nextLine());
            }

        } catch (FileNotFoundException e) {
            ExceptionHolder holder = new ExceptionHolder(e);
            holder.showExceptionMessage();
            holder.showStackTrace();

        } finally {
            if (writer != null) writer.flush();
            if (scanner != null) scanner.close();
        }
    }
}
```

### ExceptionHolder.java

```java
package master.trywith.resource.file;

public class ExceptionHolder {

    private String message;
    private StackTraceElement[] stackTraceElements;

    public ExceptionHolder(Throwable e) {
        this.message = e.getMessage();
        this.stackTraceElements = e.getStackTrace();
    }

    public void showExceptionMessage() {
        System.out.format("発生した例外 => %s %n", this.message);
    }

    public void showStackTrace() {
        System.out.println("スタックトレース:");

        for (int i = 0; i < this.stackTraceElements.length; i++) {
            System.out.format(
                "  at %s %n", this.stackTraceElements[i]);
        }
    }
}
```

### プロジェクト直下に読み込みファイルがない場合の Transcriptor.java の実行結果

```console
発生した例外 => .\testRead.txt (指定されたファイルが見つかりません。)
スタックトレース:
  at java.base/java.io.FileInputStream.open0(Native Method)
  at java.base/java.io.FileInputStream.open(FileInputStream.java:219)
  at java.base/java.io.FileInputStream.<init>(FileInputStream.java:157)
  at java.base/java.util.Scanner.<init>(Scanner.java:639)
  at master.trywith.resource.file.Transcriptor.main(Transcriptor.java:26)
```

## 解答例

https://github.com/fs5013-furi-sutao/java-bootcamp-answers/tree/main/06.master/05.try-with-resource/src/master/trywith/resource/file
